"""Create User table

Revision ID: 19a91dedbd55
Revises: 387ec286fe8e
Create Date: 2018-07-13 15:00:19.848662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19a91dedbd55'
down_revision = '387ec286fe8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('salt', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tweets', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tweets', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tweets', type_='foreignkey')
    op.drop_column('tweets', 'created_by')
    op.drop_table('users')
    # ### end Alembic commands ###
