"""add updated column

Revision ID: 387ec286fe8e
Revises: acdee0110175
Create Date: 2018-07-12 16:28:47.078105

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '387ec286fe8e'
down_revision = 'acdee0110175'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweets', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('tweets', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tweets', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('tweets', 'updated_at')
    # ### end Alembic commands ###
